"""Update invoice type

Revision ID: 23fb3386d6e8
Revises: 2f5282d6699c
Create Date: 2024-07-23 22:17:09.846169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23fb3386d6e8'
down_revision: Union[str, None] = '2f5282d6699c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('invoice_type', sa.Enum('lease', 'maintenance', 'other', 'general', name='invoicetypeenum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice', 'invoice_type')
    # ### end Alembic commands ###
