"""Changed contract num_invoices to num_invoice

Revision ID: 5a9afb14d287
Revises: d03ed768372c
Create Date: 2024-07-22 15:45:43.245195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a9afb14d287'
down_revision: Union[str, None] = 'd03ed768372c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('num_invoice', sa.Integer(), nullable=True))
    op.drop_column('contract', 'num_invoices')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('num_invoices', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('contract', 'num_invoice')
    # ### end Alembic commands ###
