"""Reverted to contract num_invoices

Revision ID: a085f07a4515
Revises: 5a9afb14d287
Create Date: 2024-07-22 15:46:17.653481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a085f07a4515'
down_revision: Union[str, None] = '5a9afb14d287'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('num_invoices', sa.Integer(), nullable=True))
    op.drop_column('contract', 'num_invoice')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('num_invoice', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('contract', 'num_invoices')
    # ### end Alembic commands ###
