"""Initial migration

Revision ID: ba533544b11f
Revises: 
Create Date: 2024-08-12 23:14:13.077367

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "ba533544b11f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
