"""Update media table

Revision ID: fe18823c34d7
Revises: 
Create Date: 2024-08-05 16:48:34.697029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe18823c34d7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('caption', sa.String(length=500), nullable=True))
    op.add_column('media', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'description')
    op.drop_column('media', 'caption')
    # ### end Alembic commands ###
